CREATE TABLE rule(
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    enable INTEGER NOT NULL,
    vibrate INTEGER NOT NULL);
CREATE TABLE calendar_rule(
    id INTEGER PRIMARY KEY NOT NULL,
    match_all INTEGER NOT NULL,
    match_title INTEGER NOT NULL,
    match_desc INTEGER NOT NULL,
    inverse_match INTEGER NOT NULL NOT NULL,
    FOREIGN KEY (id) REFERENCES rule (id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE calendar_rule_calendar(
    id INTEGER PRIMARY KEY NOT NULL,
    rule INTEGER NOT NULL,
    calendar_id INTEGER NOT NULL,
    FOREIGN KEY (rule) REFERENCES rule (id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE calendar_rule_keyword(
    id INTEGER PRIMARY KEY NOT NULL,
    rule INTEGER NOT NULL,
    word TEXT NOT NULL,
    FOREIGN KEY (rule) REFERENCES rule (id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE schedule_rule(
    id INTEGER PRIMARY KEY NOT NULL,
    begin INTEGER NOT NULL,
    end INTEGER NOT NULL,
    sunday INTEGER NOT NULL,
    monday INTEGER NOT NULL,
    tuesday INTEGER NOT NULL,
    wednesday INTEGER NOT NULL,
    thursday INTEGER NOT NULL,
    friday INTEGER NOT NULL,
    saturday INTEGER NOT NULL,
    FOREIGN KEY (id) REFERENCES rule (id) ON UPDATE CASCADE ON DELETE CASCADE);
