CREATE TABLE Rule(_id INTEGER PRIMARY KEY, name TEXT, enable INTEGER, vibrate INTEGER, matchAll INTEGER, matchTitle INTEGER, matchDesc INTEGER);
CREATE TABLE RuleCalendar(_id INTEGER PRIMARY KEY, rule INTEGER, calendarID INTEGER, FOREIGN KEY (rule) REFERENCES Rule (_id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE RuleKeyword(_id INTEGER PRIMARY KEY, rule INTEGER, word TEXT, FOREIGN KEY (rule) REFERENCES Rule (_id) ON UPDATE CASCADE ON DELETE CASCADE);
